import Replicate from 'replicate';

export class ReplicateService {
  private replicate: Replicate;

  constructor() {
    // Get API key from environment variables
    const apiKey = import.meta.env.VITE_REPLICATE_API_KEY || '';
    
    if (!apiKey || apiKey === 'your_replicate_api_key_here') {
      throw new Error('Replicate API key not configured. Please set VITE_REPLICATE_API_KEY in your .env file');
    }

    // Initialize Replicate client with proper authentication
    this.replicate = new Replicate({
      auth: apiKey,
    });
  }

  async generateSoulmateSketch(soulmateDescription: string): Promise<string> {
    try {
      // Use Google's Nano Banana for pencil sketches
      const output = await this.replicate.run(
        "google/nano-banana",
        {
          input: {
            prompt: `pencil sketch portrait, ${soulmateDescription}, detailed pencil drawing, black and white, artistic, professional, high quality, realistic, facial features, expression, character study, sketch art, pencil shading, portrait drawing, hand-drawn, sketch style, realistic proportions, detailed line work, artistic lighting`,
            width: 512,
            height: 512,
            num_inference_steps: 20,
            guidance_scale: 7.5,
            num_outputs: 1
          }
        }
      );

      // Return the first output (image URL)
      if (Array.isArray(output) && output.length > 0) {
        return output[0] as string;
      } else {
        throw new Error('No image generated');
      }
    } catch (error) {
      // Fallback to Stable Diffusion if Nano Banana fails
      try {
        const output = await this.replicate.run(
          "stability-ai/stable-diffusion:ac732df83cea7fff18b8472768c88ad041fa750ff7682a21affe81863cbe77e4",
          {
            input: {
              prompt: `pencil sketch portrait, ${soulmateDescription}, detailed pencil drawing, black and white, artistic, professional, high quality, realistic, facial features, expression, character study, sketch art, pencil shading, portrait drawing, hand-drawn, sketch style, realistic proportions, detailed line work, artistic lighting`,
              width: 512,
              height: 512,
              num_inference_steps: 20,
              guidance_scale: 7.5,
              num_outputs: 1
            }
          }
        );

        if (Array.isArray(output) && output.length > 0) {
          return output[0] as string;
        } else {
          throw new Error('No image generated by fallback model');
        }
      } catch (fallbackError) {
        throw new Error('Failed to generate sketch. Please try again later.');
      }
    }
  }

  // Test API key validity
  async testApiKey(): Promise<boolean> {
    try {
      // Test by trying to get account info
      const response = await fetch('https://api.replicate.com/v1/account', {
        headers: {
          'Authorization': `Token ${import.meta.env.VITE_REPLICATE_API_KEY}`,
        },
      });
      
      return response.ok;
    } catch (error) {
      return false;
    }
  }
}

export const replicateService = new ReplicateService();